"""Human and customer renderers driven by generation contracts."""
from __future__ import annotations

from collections import Counter
from html import escape


def render_ui_markdown(ui: dict) -> str:
    lines = ["# Existing UI Reconstruction", "", f"- Feature: `{ui['feature_id']}`", f"- Design source: `{ui['source_mode']}`", "- Figma fixture authority: `NONE`", "", "## Existing UI To Angular", ""]
    lines.extend(f"- **{item['name']}** -> `{item['target']}` ({item['source_ref']})" for item in ui["regions"])
    lines.extend(["", "## Controls", "", *[f"- **{item['name']}** -> `{item['target']}`" for item in ui["controls"]], "", "## Preserved Visual Identity", "", *[f"- `{item['token']}`: `{item['value']}`" for item in ui["styles"]], "", "## Clarifications", "", *[f"- **{item['item']}:** {item['detail']}" for item in ui["unresolved_visual_details"]], ""])
    return "\n".join(lines)


def render_ui_html(ui: dict) -> str:
    mappings = "".join(f"<article><small>{escape(item['source_ref'])}</small><h3>{escape(item['name'])}</h3><div class='arrow'>&darr;</div><code>{escape(item['target'])}</code></article>" for item in ui["regions"])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Existing UI Reconstruction</title><style>:root{{--ink:#1d1e2a;--teal:#00bdb3;--pink:#ff1770;--paper:#fff;--ground:#f0f0f0}}*{{box-sizing:border-box}}body{{margin:0;background:var(--ground);color:var(--ink);font:16px/1.55 Raleway,"Trebuchet MS",sans-serif}}header{{background:var(--ink);color:white;padding:6rem max(5vw,2rem)}}h1,h2,h3{{font-family:Georgia,serif}}h1{{font-size:clamp(3rem,8vw,6rem);margin:.1em 0}}header p{{color:#9de2dc;letter-spacing:.12em}}main{{margin:auto;padding:4rem 0;width:min(1180px,92vw)}}.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}}article{{background:white;border-top:5px solid var(--teal);padding:1.4rem}}article small{{color:#777}}.arrow{{color:var(--pink);font-size:2rem}}code{{overflow-wrap:anywhere}}@media(max-width:760px){{.grid{{grid-template-columns:1fr}}}}</style></head><body><header><p>DESIGN SOURCE &middot; EXISTING APPLICATION UI</p><h1>Recognizable experience.<br>Modern implementation.</h1><span>FIGMA FIXTURE NOT USED</span></header><main><h2>Existing UI &rarr; Angular 22</h2><p>Only mappings represented in the generated hero application are shown.</p><div class="grid">{mappings}</div></main></body></html>'''


def render_traceability_markdown(traceability: dict) -> str:
    lines = ["# Angular Hero Generation Traceability", "", "## Acceptance Criteria", ""]
    for item in traceability["acceptance_criteria"]:
        lines.extend([f"### {item['id']}", f"- Implementation: {', '.join(item['implementation_refs'])}", f"- Tests: {', '.join(item['test_refs'])}", ""])
    lines.extend(["## Technical Tasks", ""])
    lines.extend(f"- `{item['task_id']}`: `{item['status']}` - {item['detail']}" for item in traceability["technical_tasks"])
    return "\n".join(lines) + "\n"


def render_modernization_html(contract: dict) -> str:
    manifest, ui, traceability, validation = contract["manifest"], contract["ui_specification"], contract["traceability"], contract["validation"]
    statuses = Counter(item["status"] for item in manifest["task_statuses"])
    components = "".join(f"<article><small>{escape(item['kind'])}</small><h3>{escape(item['name'])}</h3><code>{escape(item['file'])}</code></article>" for item in manifest["generated_components"])
    mappings = "".join(f"<tr><td>{escape(item['name'])}</td><td>{escape(item['target'])}</td><td>{escape(item['source_ref'])}</td></tr>" for item in ui["regions"])
    apis = "".join(f"<article><b>{escape(item['method'])}</b><code>{escape(item['endpoint'])}</code><span>EXISTING API &middot; PRESERVED</span></article>" for item in manifest["preserved_api_contracts"])
    tasks = "".join(f"<li><b>{escape(item['task_id'])}</b><span>{escape(item['status'])}</span><p>{escape(item['detail'])}</p></li>" for item in manifest["task_statuses"])
    ac = "".join(f"<article><b>{escape(item['id'])}</b><span>{len(item['implementation_refs'])} implementation refs</span><span>{len(item['test_refs'])} test refs</span></article>" for item in traceability["acceptance_criteria"])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HealthClinic Angular 22 Modernization</title><style>
:root{{--ink:#1d1e2a;--teal:#00bdb3;--pink:#ff1770;--gray:#71717f;--light:#f0f0f0;--paper:#fff}}*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--light);color:var(--ink);font:16px/1.55 Raleway,"Trebuchet MS",sans-serif}}h1,h2,h3{{font-family:Georgia,serif;line-height:1.08}}h1{{font-size:clamp(3.6rem,9vw,7.8rem);margin:.15em 0;max-width:1100px}}h2{{font-size:clamp(2rem,4vw,3.3rem)}}code{{font-family:Consolas,monospace;overflow-wrap:anywhere}}.wrap{{margin:auto;width:min(1180px,92vw)}}header{{align-items:center;background:linear-gradient(125deg,#171822,#292a38);color:white;display:grid;min-height:92vh;overflow:hidden;position:relative}}header:after{{color:#ffffff08;content:'22';font:700 42vw/1 Georgia;position:absolute;right:-3vw;bottom:-12vw}}.kicker{{color:#55e0d7;font-weight:bold;letter-spacing:.15em}}.lede{{font:1.35rem/1.5 Georgia;max-width:800px}}.pills,.stats{{display:flex;flex-wrap:wrap;gap:.7rem}}.pills span{{border:1px solid #ffffff55;padding:.45rem .7rem}}section{{padding:5.5rem 0;position:relative}}section.alt{{background:white}}.stats article,.component-grid article,.api-grid article,.ac-grid article{{background:white;border-top:5px solid var(--teal);padding:1.4rem}}.stats strong{{display:block;font:2.3rem Georgia}}.component-grid,.api-grid,.ac-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}}table{{background:white;border-collapse:collapse;width:100%}}th,td{{border-bottom:1px solid #ddd;padding:1rem;text-align:left}}th{{background:var(--ink);color:white}}.api-grid article{{display:grid;gap:.8rem}}.api-grid b{{background:var(--pink);color:white;padding:.25rem .5rem;width:max-content}}.api-grid span{{color:var(--teal);font-size:.7rem;font-weight:bold;letter-spacing:.1em}}.task-list{{display:grid;grid-template-columns:repeat(2,1fr);gap:.7rem;list-style:none;padding:0}}.task-list li{{background:#252633;color:white;padding:1.2rem}}.task-list b{{color:#55e0d7;margin-right:1rem}}.task-list span{{background:#ffffff18;padding:.25rem .5rem}}.priority{{display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem}}.priority div{{background:white;border-bottom:4px solid var(--pink);padding:1rem;text-align:center}}.readiness{{background:var(--ink);color:white}}@media(max-width:800px){{.component-grid,.api-grid,.ac-grid,.task-list,.priority{{grid-template-columns:1fr}}table{{font-size:.82rem}}}}</style></head><body>
<header><div class="wrap"><p class="kicker">EXISTING UI &rarr; ANGULAR 22</p><h1>HealthClinic Dashboard, reconstructed.</h1><p class="lede">One evidence-backed hero Feature generated into a modern Nx workspace without redesigning the experience or changing backend business contracts.</p><div class="pills"><span>DESIGN SOURCE &middot; EXISTING UI</span><span>FIGMA FIXTURE &middot; NOT USED</span><span>ANGULAR 22.1.4</span><span>NX 23.2.0</span></div></div></header>
<main><section><div class="wrap"><h2>Modernization Summary</h2><div class="stats"><article><strong>{len(manifest['generated_components'])}</strong>components</article><article><strong>{len(manifest['generated_files'])}</strong>generated files</article><article><strong>4</strong>preserved APIs</article><article><strong>5 / 5</strong>hero AC traced</article></div></div></section>
<section class="alt"><div class="wrap"><h2>Existing UI &rarr; Angular 22</h2><table><thead><tr><th>Existing element</th><th>Generated element</th><th>Source reference</th></tr></thead><tbody>{mappings}</tbody></table></div></section>
<section><div class="wrap"><h2>Selected Architecture</h2><div class="priority"><div>Angular 22 + Nx</div><div>Standalone + Signals</div><div>RxJS + typed HTTP</div><div>Zoneless + lazy route</div></div><h2>Generated Components</h2><div class="component-grid">{components}</div></div></section>
<section class="alt"><div class="wrap"><h2>API Contract Preservation</h2><div class="api-grid">{apis}</div></div></section>
<section><div class="wrap"><h2>Technical Task Progress</h2><p>{statuses['IMPLEMENTED']} implemented &middot; {statuses['PARTIALLY_IMPLEMENTED']} partial &middot; {statuses['DEFERRED']} deferred &middot; {statuses['NOT_APPLICABLE']} not applicable</p><ol class="task-list">{tasks}</ol></div></section>
<section class="alt"><div class="wrap"><h2>Acceptance Criteria Coverage</h2><div class="ac-grid">{ac}</div><h2>Test Generation</h2><p>{len(manifest['generated_tests'])} test files generated. Tests are mapped to all five hero acceptance criteria and are <strong>NOT YET EXECUTED</strong>.</p></div></section>
<section><div class="wrap"><h2>Traceability</h2><div class="priority"><div>Source UI</div><div>Requirements + AC</div><div>Architecture + Tasks</div><div>Angular + Tests</div></div></div></section>
<section class="readiness"><div class="wrap"><p class="kicker">GENERATION VALIDATION &middot; {escape(validation['status'])}</p><h2>Build/Test Status: NOT YET EXECUTED</h2><p>Static generation checks pass. Prompt 064 owns dependency installation, build, test, diagnosis, repair, and revalidation.</p></div></section></main></body></html>'''
