"""Process isolation for native Tree-sitter extraction."""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Any

from polaris_modernization.models import Evidence, Fact

WORKER_TIMEOUT_SECONDS = 30
LOCAL_SOURCE_DIRECTORY = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = LOCAL_SOURCE_DIRECTORY.parent


@dataclass(frozen=True)
class ExtractionResult:
    facts: list[Fact]
    warning: dict[str, str] | None = None


def _warning(request: dict[str, str], category: str, diagnostic: str) -> ExtractionResult:
    return ExtractionResult([], {
        "source_path": request["source_path"],
        "language": request.get("language", "unknown"),
        "extractor": request.get("language", "unknown"),
        "failure_category": category,
        "diagnostic": diagnostic,
        "status": "skipped",
    })


def _fact(payload: dict[str, Any]) -> Fact:
    return Fact(
        kind=str(payload["kind"]),
        name=str(payload["name"]),
        properties=dict(payload.get("properties", {})),
        evidence=Evidence(**payload["evidence"]),
    )


def _worker_environment() -> dict[str, str]:
    environment = os.environ.copy()
    existing_pythonpath = environment.get("PYTHONPATH")
    environment["PYTHONPATH"] = str(LOCAL_SOURCE_DIRECTORY) if not existing_pythonpath else f"{LOCAL_SOURCE_DIRECTORY}{os.pathsep}{existing_pythonpath}"
    return environment


def _worker_cwd() -> str | None:
    return str(REPOSITORY_ROOT) if (REPOSITORY_ROOT / "pyproject.toml").is_file() else None


def _is_import_failure(stderr: str) -> bool:
    return "polaris_modernization" in stderr and ("ModuleNotFoundError" in stderr or "No module named" in stderr)


def _source_text(request: dict[str, str]) -> str:
    """Read safely after a native worker failure; never pass bytes to a parser."""
    return (Path(request["source_root"]) / request["source_path"]).read_text(encoding="utf-8", errors="replace")


def _opaque_reason(source_path: str, text: str) -> str | None:
    """Classify only objective dependency or generated-source signals as opaque."""
    path = source_path.replace("\\", "/").lower()
    filename = Path(path).name
    if re.search(r"(?:^|[._-])(designer|generated)(?:[._-]|$)", filename) or "<auto-generated" in text[:4096].lower():
        return "generated_or_designer_source"
    if ".min." in filename or re.search(r"(^|[-_.])vsdoc([-.]|$)", filename):
        return "minified_or_tooling_dependency"
    dependency_segments = {"node_modules", "bower_components", "vendor", "third_party", "packages", "external"}
    if dependency_segments.intersection(path.split("/")):
        return "third_party_dependency_path"
    header = text[:4096].lower()
    # Identifiable upstream library headers are stronger evidence than their
    # install location; this keeps the rule independent of any application.
    known_vendor_markers = ("jquery", "microsoft corporation", "azuremobileservices", "office javascript api")
    if (("copyright" in header or "licensed under" in header) and any(marker in header for marker in known_vendor_markers)) or "jquery ui example page" in header:
        return "third_party_dependency_header"
    # A vendor copyright/license header is evidence only when the source is also
    # formatted as a library bundle rather than ordinary application code.
    lines = text.splitlines()
    average_line_length = sum(len(line) for line in lines) / max(len(lines), 1)
    if ("copyright" in header or "licensed under" in header) and average_line_length > 240:
        return "minified_or_vendor_bundle"
    return None


def _fallback_facts(request: dict[str, str]) -> ExtractionResult:
    """Recover a small, syntax-free set of literal facts after a native crash.

    This deliberately does not attempt AST or semantic reconstruction.  It
    recognizes only declarations and literal AngularJS calls whose text can be
    proven directly, and leaves all other first-party failures visible.
    """
    try:
        text = _source_text(request)
    except OSError:
        return _warning(request, "fallback_read_failed", "Native parser crashed and the source file could not be read safely.")
    reason = _opaque_reason(request["source_path"], text)
    evidence = Evidence(request["project_id"], request["source_path"], 1, 1, "deterministic-crash-fallback", 0.5, request["source_hash"])
    if reason:
        return ExtractionResult([Fact("opaque_source", request["source_path"], evidence, {"classification": reason, "worker_exit_code": 3221225477, "semantic_understanding": False})])

    facts: list[Fact] = [Fact(
        "conservative_source",
        request["source_path"],
        evidence,
        {"classification": "first_party_native_parser_fallback", "semantic_understanding": False, "worker_exit_code": 3221225477},
    )]
    suffix = Path(request["source_path"]).suffix.lower()
    if suffix in {".js", ".ts"}:
        for match in re.finditer(r"angular\.module\(\s*['\"]([^'\"]+)['\"]", text):
            facts.append(Fact("angular_module", match.group(1), Evidence(request["project_id"], request["source_path"], text[:match.start()].count("\n") + 1, text[:match.end()].count("\n") + 1, "deterministic-crash-fallback", 0.8, request["source_hash"])))
        for kind, pattern in (("angular_controller", r"\.controller\(\s*['\"]([^'\"]+)['\"]"), ("angular_service", r"\.(?:service|factory)\(\s*['\"]([^'\"]+)['\"]"), ("angular_directive", r"\.directive\(\s*['\"]([^'\"]+)['\"]")):
            for match in re.finditer(pattern, text):
                facts.append(Fact(kind, match.group(1), Evidence(request["project_id"], request["source_path"], text[:match.start()].count("\n") + 1, text[:match.end()].count("\n") + 1, "deterministic-crash-fallback", 0.8, request["source_hash"])))
    elif suffix == ".cs":
        for match in re.finditer(r"\bclass\s+([A-Za-z_]\w*)", text):
            name = match.group(1)
            if name.endswith("Controller"):
                facts.append(Fact("controller", name, evidence, {"fallback": "literal_class_declaration"}))
    elif suffix in {".html", ".htm", ".cshtml"}:
        if suffix == ".cshtml":
            facts.append(Fact("razor_view", request["source_path"], evidence, {"fallback": "razor_file_extension"}))
        for match in re.finditer(r"<script[^>]+src\s*=\s*['\"]([^'\"]+)['\"]", text, flags=re.IGNORECASE):
            facts.append(Fact("script_asset", match.group(1), evidence, {"fallback": "literal_script_src"}))
    return ExtractionResult(facts)


def extract_file(request: dict[str, str], timeout: int = WORKER_TIMEOUT_SECONDS) -> ExtractionResult:
    """Run one extractor in a child process and return only validated fact data."""
    try:
        completed = subprocess.run(
            [sys.executable, "-m", "polaris_modernization.isolated_extraction"],
            input=json.dumps(request),
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
            env=_worker_environment(),
            cwd=_worker_cwd(),
        )
    except subprocess.TimeoutExpired:
        return _warning(request, "timeout", "Extraction worker exceeded the allowed time.")
    except OSError:
        return _warning(request, "worker_start_failed", "Extraction worker could not be started.")

    if completed.returncode != 0:
        if _is_import_failure(completed.stderr):
            return _warning(request, "worker_startup_failed", "Extraction worker could not import the analyzer package.")
        # Native access violations never count as successful AST extraction.  Only
        # proven generated/minified/dependency content may be opaque; application
        # code requires conservative literal facts or stays an explicit failure.
        if completed.returncode == 3221225477:
            return _fallback_facts(request)
        return _warning(request, "abnormal_exit", f"Extraction worker exited with code {completed.returncode}.")
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError:
        return _warning(request, "invalid_worker_output", "Extraction worker returned invalid structured output.")
    if payload.get("status") != "succeeded":
        return _warning(request, "python_extraction_error", "Extraction worker reported a Python extraction error.")
    try:
        return ExtractionResult([_fact(item) for item in payload["facts"]])
    except (KeyError, TypeError, ValueError):
        return _warning(request, "invalid_worker_output", "Extraction worker returned invalid fact data.")


def _worker(request: dict[str, str]) -> dict[str, Any]:
    root = Path(request["source_root"])
    source_path = root / request["source_path"]
    from polaris_modernization.tree_sitter_extractors.registry import extractor_for

    extractor = extractor_for(source_path)
    if extractor is None:
        raise ValueError("No extractor is available for the requested file.")
    facts = extractor.extract(source_path, root, request["source_hash"], request["project_id"])
    return {"status": "succeeded", "facts": [fact.to_dict() for fact in facts]}


def main() -> None:
    try:
        request = json.loads(sys.stdin.read())
        print(json.dumps(_worker(request), separators=(",", ":")))
    except Exception:
        # Do not emit source content or Python tracebacks from the isolated worker.
        print(json.dumps({"status": "error"}, separators=(",", ":")))


if __name__ == "__main__":
    main()
