"""Deterministic task composition from approved requirements and locked architecture."""
from __future__ import annotations

from langchain_core.runnables import RunnableLambda

from .models import TechnicalTaskModel


def _design_refs(design: dict, terms: tuple[str, ...]) -> list[str]:
    refs = []
    for group in ("screens", "components", "component_instances", "controls"):
        for item in design.get(group, []):
            if any(term in item.get("name", "").lower() for term in terms):
                refs.append(item["design_ref"])
    return list(dict.fromkeys(refs))


def _compose(context: dict) -> list[dict]:
    feature_id = context["feature"]["feature_id"]
    design = context["design"]
    dashboard_design = _design_refs(design, ("dashboard",))
    year_design = _design_refs(design, ("year", "selector"))
    summary_design = _design_refs(design, ("summary", "card"))
    no_design_note = [] if design["status"] == "AVAILABLE" else ["Implement presentation using the selected accessible design-system boundary and implementation defaults pending design input."]
    all_apis = [item["api_id"] for item in context["api_contracts"]]
    specs = [
        ("SCAFFOLD", "Establish the Angular 22 Nx delivery workspace", "Create the selected enterprise workspace foundation for the hero Feature.", ["Create the Angular 22 application in the selected Nx workspace.", "Enable standalone bootstrapping and zoneless compatibility checks.", "Apply Nx-aware lint, build, and test boundaries."], ["ARCH-001", "ARCH-003", "ARCH-006", "ARCH-017", "ARCH-052"], [], [], [], [], [], [], ["Workspace build and quality commands pass.", "Zoneless dependency compatibility is verified."], ["Nx workspace and Angular application foundation", "Initial CI quality targets"]),
        ("CONFIGURATION", "Define Dashboard domain and library boundaries", "Translate the selected modular structure into enforceable project boundaries.", ["Create domain-oriented feature, data-access, and shared UI library boundaries.", "Configure dependency constraints so presentation does not bypass integration boundaries."], ["ARCH-008", "ARCH-010", "ARCH-034"], [], [], [], [], [], ["TT-001"], ["Nx dependency validation passes.", "Boundary rules prevent direct cross-domain imports."], ["Dashboard feature boundary", "Dashboard data-access boundary"]),
        ("DESIGN_SYSTEM", "Establish the accessible shared design-system boundary", "Provide reusable presentation primitives for Dashboard delivery.", [*no_design_note, "Translate only normalized design tokens and reusable components when design input is available.", "Keep design guidance subordinate to approved requirements."], ["ARCH-009", "ARCH-046", "ARCH-048"], [], [], [], [], dashboard_design + summary_design, ["TT-001"], ["Shared primitives meet keyboard, contrast, and responsive validation expectations.", "No design-derived business behavior is introduced."], ["Shared design-system library", "Dashboard presentation primitives"]),
        ("API", "Model the four existing Dashboard API contracts", "Create typed client-side models without changing existing backend semantics.", ["Represent each approved existing method, route, parameter, and response model exactly.", "Keep existing contracts distinct from future target facade design.", "Use the selected typed Angular HTTP strategy."], ["ARCH-010", "ARCH-037", "ARCH-038"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], [], all_apis, [], ["TT-002"], ["Contract tests cover all four approved APIs.", "No replacement or additional existing API is declared."], ["Typed Dashboard API models", "Existing API contract tests"]),
        ("GATEWAY", "Plan provider-neutral Gateway routing and policies", "Represent the selected target ingress layer without implementing a product or changing business APIs.", ["Configure future routing to preserve the four existing backend contracts.", "Define policy concerns for authentication, correlation propagation, and observability.", "Leave provider selection as a later configuration decision."], ["ARCH-039", "ARCH-044", "ARCH-051"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], [], all_apis, [], ["TT-004"], ["Route mapping review proves all existing contracts are preserved.", "No gateway product is selected by this task."], ["Target Gateway routing plan", "Gateway policy checklist"]),
        ("BFF", "Design the future Dashboard BFF boundary", "Plan the selected frontend-specific integration boundary while preserving backend behavior.", ["Label every future frontend-facing facade as TARGET_CONTRACT_TO_BE_DESIGNED.", "Map justified orchestration to the four existing API contracts without inventing business rules.", "Define tenant context, correlation, and error propagation responsibilities."], ["ARCH-041", "ARCH-044", "ARCH-051"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], [], all_apis, [], ["TT-005"], ["Review confirms no future facade is represented as an existing API.", "Backend method, path, and response semantics remain unchanged."], ["BFF responsibility design", "TARGET_CONTRACT_TO_BE_DESIGNED register"]),
        ("INTEGRATION", "Implement the Angular-to-BFF client boundary", "Keep the browser integration aligned to the selected target topology.", ["Create a typed integration port for the future BFF contract.", "Mark the port contract TARGET_CONTRACT_TO_BE_DESIGNED until approved.", "Keep the existing API contracts traceable behind the target boundary."], ["ARCH-037", "ARCH-038", "ARCH-041"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], [], all_apis, [], ["TT-006"], ["The Dashboard feature depends on the integration port rather than backend-specific transport.", "Contract status remains explicit."], ["Dashboard integration port", "Typed integration adapters"]),
        ("ROUTING", "Configure the lazy Operational Dashboard route", "Expose the approved Dashboard experience through the selected routing strategy.", ["Register a lazy feature route for the standalone Dashboard shell.", "Use functional route APIs and a functional guard boundary without defining an identity provider."], ["ARCH-024", "ARCH-025", "ARCH-026", "ARCH-028"], ["FR-01"], ["US-03"], ["ac-operational-dashboard-insights-open-operational-dashboard-001", "ac-operational-dashboard-insights-open-operational-dashboard-002"], [], dashboard_design, ["TT-002"], ["Route loading is lazy and resolves to the standalone shell.", "Approved Dashboard access criteria are covered."], ["Dashboard route configuration", "Route activation tests"]),
        ("UI", "Implement the standalone Operational Dashboard shell", "Create the feature container and presentation regions without changing functional scope.", ["Build a standalone shell within the Dashboard feature boundary.", "Expose year selection and approved expense, patient, and clinic summary regions.", *no_design_note], ["ARCH-003", "ARCH-034", "ARCH-046"], ["FR-01", "FR-02", "FR-03", "FR-04"], ["US-01", "US-02", "US-03"], ["ac-operational-dashboard-insights-open-operational-dashboard-001", "ac-operational-dashboard-insights-open-operational-dashboard-002"], [], dashboard_design + summary_design, ["TT-003", "TT-008"], ["Shell renders all approved presentation regions.", "No unsupported field, metric, or business rule is added."], ["Standalone Dashboard shell", "Summary presentation composition"]),
        ("STATE", "Implement Dashboard Signals and RxJS data flow", "Separate synchronous UI state from asynchronous report retrieval.", ["Use Signals for selected-year, loading, error, and derived presentation state.", "Use RxJS for HTTP cancellation and composition across approved contracts.", "Do not embed transport calls in presentation components."], ["ARCH-012", "ARCH-013", "ARCH-015", "ARCH-016", "ARCH-021"], ["FR-02", "FR-03", "FR-04"], ["US-01", "US-02"], ["ac-operational-dashboard-insights-access-yearly-operational-reports-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-002"], ["API-02", "API-03", "API-04"], year_design + summary_design, ["TT-004", "TT-007", "TT-009"], ["Year changes cancel stale asynchronous work.", "Derived UI state remains deterministic and independently tested."], ["Dashboard feature state", "RxJS report orchestration"]),
        ("SECURITY_CONTEXT", "Propagate tenant context through the target integration path", "Preserve organization-aware behavior without selecting an identity provider.", ["Retrieve the approved current-tenant contract through the integration boundary.", "Propagate tenant and correlation context through Angular, Gateway, and BFF responsibilities.", "Keep authentication provider and browser session implementation as explicit clarifications."], ["ARCH-026", "ARCH-038", "ARCH-044"], ["FR-05"], ["US-01", "US-02"], ["ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-002"], ["API-01"], [], ["TT-005", "TT-006", "TT-010"], ["Tenant context uses only the approved contract.", "Tests prove context propagation and no provider assumption."], ["Tenant context service", "Context propagation tests"]),
        ("UI", "Implement yearly report and clinic summary presentation", "Present approved operational information while preserving unresolved field-level questions.", ["Connect expense and patient regions to selected-year state.", "Connect clinic summary presentation to current organization context.", "Do not invent report fields or metrics pending approved clarifications."], ["ARCH-003", "ARCH-034", "ARCH-046"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], ["ac-operational-dashboard-insights-access-yearly-operational-reports-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-002"], ["API-01", "API-02", "API-03", "API-04"], summary_design, ["TT-010", "TT-011"], ["Each region is driven by approved state and API references.", "Unknown fields remain documented rather than fabricated."], ["Expense summary region", "Patient summary region", "Clinic summary region"]),
        ("ACCESSIBILITY", "Validate responsive and accessible Dashboard behavior", "Apply the selected accessibility strategy across the implemented experience.", ["Verify semantic structure, keyboard operation, focus behavior, labels, and responsive reflow.", "Use normalized responsive hints only when present and retain implementation defaults otherwise."], ["ARCH-046", "ARCH-048"], ["FR-01", "FR-02", "FR-03", "FR-04"], ["US-01", "US-02", "US-03"], [], [], dashboard_design + year_design + summary_design, ["TT-012"], ["Automated accessibility checks pass.", "Manual keyboard and responsive review is recorded without unsupported compliance claims."], ["Accessibility validation report", "Responsive behavior tests"]),
        ("OBSERVABILITY", "Add correlated Dashboard telemetry and failure handling", "Make target integration failures diagnosable without selecting a telemetry vendor.", ["Propagate correlation context across browser, Gateway, BFF, and existing API boundaries.", "Instrument report loading and technical failures without recording sensitive tenant data.", "Keep vendor configuration external to feature code."], ["ARCH-038", "ARCH-039", "ARCH-041", "ARCH-051"], ["FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02"], [], all_apis, [], ["TT-007", "TT-010", "TT-011"], ["Correlation propagation is covered by integration tests.", "Telemetry contains no sensitive context values."], ["Correlation interceptor", "Dashboard telemetry events"]),
        ("TEST", "Implement unit and component coverage", "Verify state, UI, routing, contract, and accessibility behavior at component boundaries.", ["Cover Signals-derived state and RxJS cancellation.", "Cover standalone shell and summary regions against approved requirements.", "Cover typed contract and tenant-context boundaries."], ["ARCH-049", "ARCH-052"], ["FR-01", "FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02", "US-03"], [], all_apis, [], ["TT-012", "TT-013", "TT-014"], ["Unit and component suites pass in affected Nx targets.", "Tests retain exact approved API references."], ["Dashboard unit tests", "Dashboard component tests"]),
        ("TEST", "Automate approved Dashboard acceptance flows with Playwright", "Provide end-to-end evidence for the five hero Feature acceptance criteria.", ["Automate Dashboard route access, yearly reporting, and tenant-aware summary behavior.", "Map each scenario to an authoritative acceptance-criteria reference.", "Use controlled test data without redefining unresolved report fields."], ["ARCH-050", "ARCH-052"], ["FR-01", "FR-02", "FR-03", "FR-04", "FR-05"], ["US-01", "US-02", "US-03"], ["ac-operational-dashboard-insights-access-yearly-operational-reports-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-001", "ac-operational-dashboard-insights-view-tenant-aware-dashboard-summary-002", "ac-operational-dashboard-insights-open-operational-dashboard-001", "ac-operational-dashboard-insights-open-operational-dashboard-002"], all_apis, [], ["TT-015"], ["All five approved criteria have executable scenario traceability.", "End-to-end suite passes against the target integration boundary."], ["Playwright Dashboard suite", "Acceptance-criteria traceability report"]),
    ]
    decisions = {item["id"]: item for item in context["architecture"]["decisions"]}
    tasks = []
    for order, spec in enumerate(specs, 1):
        category, title, objective, requirements, arch_refs, fr_refs, stories, ac_refs, api_refs, design_refs, dependencies, validation, deliverables = spec
        adr_refs = list(dict.fromkeys(decisions[ref]["adr_ref"] for ref in arch_refs if decisions[ref].get("adr_ref")))
        trace = [f"Feature:{feature_id}", *[f"FR:{item}" for item in fr_refs], *[f"Story:{item}" for item in stories], *[f"AC:{item}" for item in ac_refs], *[f"Architecture:{item}" for item in arch_refs], *[f"ADR:{item}" for item in adr_refs], *[f"API:{item}" for item in api_refs], *[f"Design:{item}" for item in design_refs]]
        tasks.append(TechnicalTaskModel(
            task_id=f"TT-{order:03d}", feature_id=feature_id, title=title, objective=objective,
            category=category, description=f"{objective} This task implements the locked architecture selection and does not make a new architecture decision.",
            implementation_requirements=requirements, architecture_decision_refs=arch_refs, adr_refs=adr_refs,
            functional_requirement_refs=fr_refs, story_refs=stories, acceptance_criteria_refs=ac_refs,
            api_refs=api_refs, design_refs=list(dict.fromkeys(design_refs)), dependencies=dependencies,
            validation_requirements=validation, deliverables=deliverables, implementation_order=order,
            blocking=False, open_questions=[], traceability=trace,
        ).model_dump(mode="json"))
    return tasks


def technical_task_chain() -> RunnableLambda:
    """Offline structured transformation; it performs no LLM or network call."""
    return RunnableLambda(_compose)
